module.exports = {
  //  state
  METAMASK_STATUS_LOADING: 'METAMASK_STATUS_LOADING',
  METAMASK_NETWORK_LOADING: 'METAMASK_NETWORK_LOADING',
  METAMASK_NETWORK_NOT_LOADED: 'METAMASK_NETWORK_NOT_LOADED',
  METAMASK_STATUS_NOT_LOADED: 'METAMASK_STATUS_NOT_LOADED',
  //  actions
  CHECK_METAMASK: 'CHECK_METAMASK'
}
