module.exports = {
  //  state
  METAMASK_STATUS_LOADING: 'METAMASK_STATUS_LOADING',
  METAMASK_NETWORK_LOADING: 'METAMASK_NETWORK_LOADING',
  METAMASK_NETWORK_NOT_LOADED: 'METAMASK_NETWORK_NOT_LOADED',
  METAMASK_STATUS_NOT_LOADED: 'METAMASK_STATUS_NOT_LOADED',
  COMPANY: 'COMPANY',
  EMPLOYEE: 'EMPLOYEE',
  NOT_LOGGED_IN: 'NOT_LOGGED_IN',
  LOGGED_IN: 'LOGGED_IN',
  NONE: 'NONE',
  //  actions
  SET_USER_ROLE: 'SET_USER_ROLE',
  SIGN_IN: 'SIGN_IN',
  CHECK_METAMASK: 'CHECK_METAMASK'
}
